### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by 715670119** [AnyListen/YaVipCore#10]
大佬大佬，新年快乐~
咳咳，我提建议了哈
就是……这是个电脑软件嘛，所以流量不是问题，部分人（我也在内），磁盘较小，所以尽量不下东西，大佬能弄个歌单功能吗，就是把喜欢的歌直接在线收藏到歌单里，每次启动软件，在线播放歌单里的歌~~~emmm就是在线播放列表……
对了，建议去除歌曲来源显示，因为……不便明说，大佬是聪明人哈哈

**Comment by AnyListen** [comment]
暂时不会开发更多功能，如果需要歌单，推荐你使用 listenOne 这个能够满足你的需求
