### ISSUE TITLE
网易音乐下载

### ISSUE THREAD

**Issue by LuZWCHA** [AnyListen/YaVipCore#9]
怎么处理网易的特殊格式音乐，现在网易的接口下载不了无损
同理酷狗Hifi 也有自己viper格式的音乐，怎么处理这些加密后的格式

**Comment by AnyListen** [comment]
暂时没有时间研究网易云音乐，有空跟进

**Comment by waguansi** [comment]
暂时可以用这个
来源：贴吧
NCM文件转化器批处理版.rar
https://pan.baidu.com/s/1XwHiNjp4G19dIOICRiUcAw 密码：1111

**Comment by godps** [comment]
反馈一些问题：部分音乐音质不正确，标的无损实际下载出来是低码率的mp3；pre3版本的虾米音乐搜不出任何资源；pre4版本虾米能搜出来但是点下载就崩溃，另外网易云又搜不出资源来了
